PRJ = initest
SRC = ini_test.c mist_cfg.c ini_parser.c

OBJ = $(SRC:.c=.o)
DEP = $(SRC:.c=.d)

CFLAGS = -Wno-attributes
CPPFLAGS  = -DINI_PARSER_TEST

# Our target.
all: $(PRJ)

$(PRJ): $(OBJ)
	$(CC) -o $@ $(OBJ)

clean:
	rm -f $(OBJ) $(PRJ)
